controllers/CartController.php
<?php


namespace app\controllers;
use app\models\OrderItem;
use app\models\Orders;
use app\models\Products;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\web\HttpException;


class CartController extends AppController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionAddCart(){
        if(Yii::$app->request->isAjax){
            $id = Yii::$app->request->get('id');
            $son = Yii::$app->request->get('son');
            $products = new Products();
            $model = Products::findOne($id);
            debug($son);
            if(!empty($son)){
                $products->saveDb($model, $son);
                $products->addToCart($model, $son);
            }
            else{
                $products->saveDb($model);
                $products->addToCart($model);
            }
            $this->layout = false;
            return $this->render('cart', compact('model'));
        }
        else{
            return $this->redirect(Yii::$app->request->referrer);
        }
    }

    public function actionRemove(){
        $product = new Products();
        $product_id = Yii::$app->request->get('id');
        $order = Orders::findOne([
            'user_id' => Yii::$app->user->identity->id,
            'product_id' => $product_id
        ]);
        $product->DelItems($product_id);
        $this->layout = false;
        $model = Orders::find()->all();
        if($order->delete()){
            Yii::$app->session->setFlash('soni', $_SESSION['cart.son']);
            return $this->render('cart', compact('model'));
        }
        else{
            return false;
        }
    }

    public function actionWishList(){
        $model = Orders::find()
        ->asArray()
        ->where(['user_id' => Yii::$app->user->identity->id])
        ->all();
        return $this->render('carts', compact('model'));
    }

    public function actionDelItems(){
        $id = Yii::$app->request->get('id');
        $order = Orders::findOne($id);
        $product = new Products();
        $product->DelItems($order->product_id);
        if($order->delete()){
            Yii::$app->session->setFlash('success', "Ma'lumot o'chirildi!");
            return $this->redirect(['cart/wish-list']);
        }
        else{
            Yii::$app->session->setFlash('success', "Ma'lumot o'chirilmadi!");
            return $this->redirect(['cart/wish-list']);
        }
    }

    public function actionOformit(){
        $id = Yii::$app->request->get('id');
        $order = Orders::findOne([
            'id' => $id
        ]);
        $product = Products::findOne([
            'id' => $order->product_id
        ]);

        $model = new OrderItem();

        if($model->load(Yii::$app->request->post())){
            Yii::$app->mailer->compose('order', ['session' => $_SESSION['cart']])
                ->setFrom(['admin@mail.ru' => 'Umidjon'])
                ->setTo($model->email)
                ->setSubject($model->product_name)
                ->send();
            $model->user_id = Yii::$app->user->identity->id;
            $model->product_id = $product->id;
            $model->status = 'active';
            $row = OrderItem::findOne([
                'user_id' => Yii::$app->user->identity->id,
                'product_id' => $product->id
            ]);
            if(!empty($row)){
                $row->soni += $model->soni;
                if($row->save()){
                    Yii::$app->session->setFlash('success', "Buyurtmangiz yuborildi!");
                    $product->DelItems($order->product_id);
                    $order->delete();
                    return $this->redirect(['cart/wish-list']);
                }
                else{
                    Yii::$app->session->setFlash('error', "Ma'lumotlar yuborilmadi!");
                    return $this->refresh();
                }
            }
            else{
                if($model->save()){
                    Yii::$app->session->setFlash('success', "Buyurtmangiz yuborildi!");
                    $product->DelItems($order->product_id);
                    $order->delete();
                    return $this->redirect(['cart/wish-list']);
                }
                else{
                    Yii::$app->session->setFlash('error', "Ma'lumotlar yuborilmadi!");
                    return $this->refresh();
                }
            }
        }
        return $this->render('ofor', compact('order', 'product', 'model'));
    }

    public function actionSaveAll(){
        $user_id = Yii::$app->user->identity->id;
        $product = new Products();
        $orders = Orders::find()
            ->asArray()
            ->where(['user_id' => $user_id])
            ->all();
        $model = new OrderItem();
        $array = [];

        if($model->load(Yii::$app->request->post())){
            $n = $model->fullname;
            $email = $model->email;
            $address = $model->address;
            $phone = $model->phone;
            foreach ($orders as $k => $r){
                $del = Orders::findOne($r['id']);
                $row = OrderItem::findOne([
                    'user_id' => $user_id,
                    'product_id' => $r['product_id'],
                    'status' => 'active'
                ]);
                if(!empty($row)){
                    $row->soni += $r['son'];
                    $row->save(false);
                }
                else{
                    $model->fullname = $n;
                    $model->email = $email;
                    $model->phone = $phone;
                    $model->address = $address;
                    $model->user_id = $user_id;
                    $model->product_name = $r['name'];
                    $model->product_id = $r['product_id'];
                    $model->sum = $r['sum'];
                    $model->soni = $r['son'];
                    $model->images = $r['images'];
                    $model->status = 'active';
                    if($model->save()){
                        $model = new OrderItem();
                    }
                }
                $product->DelItems($del->product_id);
                $del->delete();
            }
            Yii::$app->session->setFlash('success', "Buyurtmangiz qabul qilindi!");
            return $this->redirect(['main/index']);
        }
        return $this->render('save', compact('model', 'orders'));
    }
}

controllers/MainController.php
<?php

namespace app\controllers;
use app\models\Category;
use app\models\Orders;
use app\models\Products;
use app\models\Signup;
use app\models\Users;
use Yii;
use yii\bootstrap\ActiveForm;
use yii\data\Pagination;
use yii\web\HttpException;
use app\models\LoginForm;


class MainController extends AppController
{

    public function actionIndex(){
        $this->setMeta('Xarid savatcha');
        $model = Products::find()
            ->asArray()
            ->where(['new' => 1])
            ->orderBy(['id' => SORT_DESC])
            ->all();
        return $this->render('index', compact('model'));
    }

    public function actionCategory(){
        $id = Yii::$app->request->get('id');
        $model = Category::findOne(['id' => $id]);
        $products = Products::find()
        ->asArray()
        ->where(['category_id' => $model->id]);
        $page = new Pagination([
            'totalCount' => $products->count(),
            'pageSize' => 9,
            'forcePageParam' => false,
            'pageSizeParam' => false
        ]);
        $products = $products
            ->offset($page->offset)
            ->limit($page->limit)
            ->all();
        $this->setMeta($model->name, $model->keywords, $model->description);
        return $this->render('category', compact('page','model', 'products'));
    }
    public function actionProducts(){
        $id = Yii::$app->request->get('id');
        $model = Products::findOne($id);
        $this->setMeta($model->name, $model->keywords, $model->description);
        return $this->render('products', compact('model'));
    }

    // ajax
    public function actionDataOne(){
        $id = Yii::$app->request->get('id');
        $model = Products::findOne($id);
        if(Yii::$app->request->isAjax){
            $this->layout = false;
            return $this->renderAjax('data_one', compact('model'));
        }
        return $this->render('data_one', compact('model'));
    }

    public function actionSignup(){
        $model = new Signup();
        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())){
            Yii::$app->response->format = 'json';
            return ActiveForm::validate($model);
        }

        if($model->load(Yii::$app->request->post())){
            $model->status = 'active';
            if($model->signup()){
                return $this->redirect(['main/login']);
            }
            else{
                Yii::$app->session->setFlash('error', 'Malumotlar saqlanmadi!');
                return $this->refresh();
            }
        }
        return $this->render('signup', compact('model'));
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

}

views/main/data_one.php
<?php
use yii\helpers\Url;
?>
<!-- Product Thumbnail Start -->
<div class="main-product-thumbnail pb-100">
    <div class="container">
        <div class="row">
            <div class="col-sm-5">
                <img id="big-img" src="<?=Url::base()?>/img/new-products/1_1.jpg" data-zoom-image="<?=Url::base()?>/img/new-products/1_1.jpg" alt="product-image" />

                <div id="small-img" class="mt-20">
                    <div class="thumb-menu owl-carousel owl-loaded owl-drag">
                        <div class="owl-stage-outer">
                            <div class="owl-stage" style="transform: translate3d(0px, 0px, 0px); transition: all 0s ease 0s; width: 592px;">
                                <div class="owl-item active" style="width: 103.25px; margin-right: 15px;">
                                    <a  href="#" data-image="<?=Url::base()?>/img/new-products/1_2.jpg" data-zoom-image="<?=Url::base()?>/img/new-products/1_2.jpg">
                                        <img class="images_slider" src="<?=Url::base()?>/img/new-products/1_2.jpg" alt="product-image">
                                    </a></div>
                                <div class="owl-item active" style="width: 103.25px; margin-right: 15px;"><a href="#" data-image="<?=Url::base()?>/img/new-products/2_1.jpg"  data-zoom-image="<?=Url::base()?>/img/new-products/2_1.jpg">
                                        <img class="images_slider" src="<?=Url::base()?>/img/new-products/2_1.jpg" alt="product-image">
                                    </a></div>
                                <div class="owl-item active"  style="width: 103.25px; margin-right: 15px;"><a href="#" data-image="<?=Url::base()?>/img/new-products/2_2.jpg"  data-zoom-image="<?=Url::base()?>/img/new-products/2_2.jpg">
                                        <img class="images_slider" src="<?=Url::base()?>/img/new-products/2_2.jpg" alt="product-image">
                                    </a></div>
                                <div class="owl-item active" style="width: 103.25px; margin-right: 15px;"><a href="#"  data-image="<?=Url::base()?>/img/new-products/2_2.jpg" data-zoom-image="<?=Url::base()?>/img/new-products/2_2.jpg">
                                        <img src="<?=Url::base()?>/img/new-products/2_2.jpg" alt="product-image" class="images_slider">
                                    </a></div>


                            </div>
                        </div>
                        <div class="owl-nav"><div class="owl-prev"><i class="fa fa-angle-left"></i></div><div class="owl-next"><i class="fa fa-angle-right"></i></div></div><div class="owl-dots"></div></div>
                </div>
            </div>
            <!-- Thumbnail Description Start -->
            <div class="col-sm-7">
                <div class="thubnail-desc fix">
                    <h2 class="product-header"><?=$model->name?></h2>
                    <!-- Product Rating Start -->
                    <div class="rating-summary fix mtb-20">
                        <div class="rating f-left mr-10">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                        </div>
                        <div class="rating-feedback f-left">
                            <a href="#">0 reviews</a> /
                            <a href="#">Write a review</a>
                        </div>
                    </div>
                    <!-- Product Rating End -->
                    <!-- Product Price Start -->
                    <div class="pro-price mb-20">
                        <ul class="pro-price-list">
                            <li class="price">$<?=$model->sum?></li>
                        </ul>
                    </div>
                    <!-- Product Price End -->
                    <!-- Product Price Description Start -->
                    <div class="product-price-desc">
                        <ul class="pro-desc-list">
                            <li>Product Code: <span>SAMI</span></li>
                            <li>Reward Points: <span>1000</span></li>
                            <li>Availability: <span>in Stock</span></li>
                        </ul>
                    </div>
                    <!-- Product Price Description End -->
                    <!-- Product Box Quantity Start -->
                    <div class="box-quantity mtb-20">
                        <div class="quantity-item">
                            <label>Qty: </label>
                            <div class="cart-plus-minus">
                                <input class="cart-plus-minus-box" type="text" name="qtybutton" value="0">
                            </div>
                        </div>
                    </div>
                    <!-- Product Box Quantity End -->
                    <!-- Product Button Actions Start -->
                    <div class="product-button-actions">
                        <button class="add-to-cart">add to cart</button>
                        <a href="wish-list.html" data-toggle="tooltip" title="Add to Wishlist" class="same-btn mr-15"><i class="pe-7s-like"></i></a>
                        <button data-toggle="tooltip" title="Compare this Product" class="same-btn"><i class="pe-7s-repeat"></i></button>
                    </div>
                    <!-- Product Button Actions End -->
                    <!-- Product Social Link Share Start -->
                    <div class="social-shared">
                        <ul>
                            <li class="f-book">
                                <a href="#">
                                    <span><i class="fa fa-thumbs-o-up" aria-hidden="true"></i></span>
                                    <span>like</span>
                                    <span>1</span>
                                </a>
                            </li>
                            <li class="twitter">
                                <a href="#">
                                    <span><i class="fa fa-twitter" aria-hidden="true"></i></span>
                                    <span>tweet</span>
                                </a>
                            </li>
                            <li class="pinterest">
                                <a href="#">
                                    <span><i class="fa fa-google" aria-hidden="true"></i></span>
                                    <span>plus</span>
                                </a>
                            </li>
                            <!-- Product Social Link Share Dropdown Start -->
                            <li class="share-post">
                                <a href="#">
                                    <span><i class="fa fa-plus-square" aria-hidden="true"></i></span>
                                    <span>share</span>
                                </a>
                                <ul class="sharable-dropdown">
                                    <li><a href="#"><i class="fa fa-facebook-official" aria-hidden="true"></i>facebook</a></li>
                                    <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i>twitter</a></li>
                                    <li><a href="#"><i class="fa fa-print" aria-hidden="true"></i>print</a></li>
                                    <li><a href="#"><i class="fa fa-envelope-o" aria-hidden="true"></i>email</a></li>
                                    <li><a href="#"><i class="fa fa-pinterest-square" aria-hidden="true"></i>pinterest</a></li>
                                    <li><a href="#"><i class="fa fa-google-plus-square" aria-hidden="true"></i>google+</a></li>
                                    <li><a href="#"><i class="fa fa-plus-square" aria-hidden="true"></i>more(99)</a></li>
                                </ul>
                            </li>
                            <!-- Product Social Link Share Dropdown End -->
                        </ul>
                        <hr>
                        <p><?=$model->content?></p>
                    </div>
                    <!-- Product Social Link Share End -->
                </div>
            </div>
            <!-- Thumbnail Description End -->
        </div>
        <!-- Row End -->
    </div>
    <!-- Container End -->
</div>
<!-- Product Thumbnail End -->

views/main/login.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login va Parol orqali kirish';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login container">
    <h5 class="alert alert-danger"><?= Html::encode($this->title) ?></h5>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/main/products.php
<?php
    use yii\helpers\Url;
?>
<!-- Page Breadcrumb Start -->
<div class="main-breadcrumb mb-100" style="background: rgba(0, 0, 0, 0) url(<?=Url::base().'/img/blog/5.png'?>) no-repeat scroll center center / cover;">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="breadcrumb-content text-center ptb-70">
                    <h1><?=$model->name?></h1>
                    <ul class="breadcrumb-list breadcrumb">
                        <li><a href="<?=Url::home()?>">bosh sahifa</a></li>
                        <li><a href="#"><?=$model->name; ?></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Page Breadcrumb End -->
<!-- Product Thumbnail Start -->
<div class="main-product-thumbnail pb-100">
    <div class="container">
        <div class="row">
            <div class="col-sm-5">
                <img id="big-img" src="<?=Url::base()?>/img/new-products/1_1.jpg" data-zoom-image="<?=Url::base()?>/img/new-products/1_1.jpg" alt="product-image" />

                <div id="small-img" class="mt-20">

                    <div class="thumb-menu owl-carousel">
                        <a href="#" data-image="<?=Url::base()?>/img/new-products/1_2.jpg" data-zoom-image="<?=Url::base()?>/img/new-products/1_2.jpg">
                            <img src="<?=Url::base()?>/img/new-products/1_2.jpg" alt="product-image" />
                        </a>

                        <a href="#" data-image="<?=Url::base()?>/img/new-products/2_1.jpg" data-zoom-image="<?=Url::base()?>/img/new-products/2_1.jpg">
                            <img src="<?=Url::base()?>/img/new-products/2_1.jpg" alt="product-image" />
                        </a>

                        <a href="#" data-image="<?=Url::base()?>/img/new-products/2_2.jpg" data-zoom-image="<?=Url::base()?>/img/new-products/2_2.jpg">
                            <img src="<?=Url::base()?>/img/new-products/2_2.jpg" alt="product-image" />
                        </a>

                        <a href="#" data-image="<?=Url::base()?>/img/new-products/3_1.jpg" data-zoom-image="<?=Url::base()?>/img/new-products/3_1.jpg">
                            <img src="<?=Url::base()?>/img/new-products/3_1.jpg" alt="product-image" />
                        </a>

                        <a href="#" data-image="<?=Url::base()?>/img/new-products/2_1.jpg" data-zoom-image="<?=Url::base()?>/img/new-products/2_1.jpg">
                            <img src="<?=Url::base()?>/img/new-products/2_1.jpg" alt="product-image" />
                        </a>
                    </div>
                </div>
            </div>
            <!-- Thumbnail Description Start -->
            <div class="col-sm-7">
                <div class="thubnail-desc fix">
                    <h2 class="product-header"><?=$model->name?></h2>
                    <!-- Product Rating Start -->
                    <div class="rating-summary fix mtb-20">
                        <div class="rating f-left mr-10">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                        </div>
                        <div class="rating-feedback f-left">
                            <a href="#">0 reviews</a> /
                            <a href="#">Write a review</a>
                        </div>
                    </div>
                    <!-- Product Rating End -->
                    <!-- Product Price Start -->
                    <div class="pro-price mb-20">
                        <ul class="pro-price-list">
                            <li class="price">$<?=$model->sum?></li>
                        </ul>
                    </div>
                    <!-- Product Price End -->
                    <!-- Product Price Description Start -->
                    <div class="product-price-desc">
                        <ul class="pro-desc-list">
                            <li>Product Code: <span>SAMI</span></li>
                            <li>Reward Points: <span>1000</span></li>
                            <li>Availability: <span>in Stock</span></li>
                        </ul>
                    </div>
                    <!-- Product Price Description End -->
                    <!-- Product Box Quantity Start -->
                    <div class="box-quantity mtb-20">
                        <div class="quantity-item">
                            <label>Qty: </label>
                            <div class="cart-plus-minus">
                                <input class="cart-plus-minus-box" type="text" name="qtybutton" value="1">
                            </div>
                        </div>
                    </div>
                    <!-- Product Box Quantity End -->
                    <!-- Product Button Actions Start -->
                    <div class="product-button-actions">
                        <button href="<?=Url::to(['cart/add-cart'])?>" data-id="<?=$model->id; ?>" class="add-to-cart" id="add-to-cart">Add-to-cart</button>
                        <a href="wish-list.html" data-toggle="tooltip" title="Add to Wishlist" class="same-btn mr-15"><i class="pe-7s-like"></i></a>
                        <button data-toggle="tooltip" title="Compare this Product" class="same-btn"><i class="pe-7s-repeat"></i></button>
                    </div>
                    <!-- Product Button Actions End -->
                    <!-- Product Social Link Share Start -->
                    <div class="social-shared">
                        <ul>
                            <li class="f-book">
                                <a href="#">
                                    <span><i class="fa fa-thumbs-o-up" aria-hidden="true"></i></span>
                                    <span>like</span>
                                    <span>1</span>
                                </a>
                            </li>
                            <li class="twitter">
                                <a href="#">
                                    <span><i class="fa fa-twitter" aria-hidden="true"></i></span>
                                    <span>tweet</span>
                                </a>
                            </li>
                            <li class="pinterest">
                                <a href="#">
                                    <span><i class="fa fa-google" aria-hidden="true"></i></span>
                                    <span>plus</span>
                                </a>
                            </li>
                            <!-- Product Social Link Share Dropdown Start -->
                            <li class="share-post">
                                <a href="#">
                                    <span><i class="fa fa-plus-square" aria-hidden="true"></i></span>
                                    <span>share</span>
                                </a>
                                <ul class="sharable-dropdown">
                                    <li><a href="#"><i class="fa fa-facebook-official" aria-hidden="true"></i>facebook</a></li>
                                    <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i>twitter</a></li>
                                    <li><a href="#"><i class="fa fa-print" aria-hidden="true"></i>print</a></li>
                                    <li><a href="#"><i class="fa fa-envelope-o" aria-hidden="true"></i>email</a></li>
                                    <li><a href="#"><i class="fa fa-pinterest-square" aria-hidden="true"></i>pinterest</a></li>
                                    <li><a href="#"><i class="fa fa-google-plus-square" aria-hidden="true"></i>google+</a></li>
                                    <li><a href="#"><i class="fa fa-plus-square" aria-hidden="true"></i>more(99)</a></li>
                                </ul>
                            </li>
                            <!-- Product Social Link Share Dropdown End -->
                        </ul>
                        <hr>
                        <p><?=$model->content?></p>
                    </div>
                    <!-- Product Social Link Share End -->
                </div>
            </div>
            <!-- Thumbnail Description End -->
        </div>
        <!-- Row End -->
    </div>
    <!-- Container End -->
</div>
<!-- Product Thumbnail End -->