controllers/CartController.php
<?php


namespace app\controllers;
use app\models\OrderItem;
use app\models\Orders;
use app\models\Products;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\web\HttpException;


class CartController extends AppController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionAddCart(){
        if(Yii::$app->request->isAjax){
            $id = Yii::$app->request->get('id');
            $son = Yii::$app->request->get('son');
            $products = new Products();
            $model = Products::findOne($id);
            debug($son);
            if(!empty($son)){
                $products->saveDb($model, $son);
                $products->addToCart($model, $son);
            }
            else{
                $products->saveDb($model);
                $products->addToCart($model);
            }
            $this->layout = false;
            return $this->render('cart', compact('model'));
        }
        else{
            return $this->redirect(Yii::$app->request->referrer);
        }
    }

    public function actionRemove(){
        $product = new Products();
        $product_id = Yii::$app->request->get('id');
        $order = Orders::findOne([
            'user_id' => Yii::$app->user->identity->id,
            'product_id' => $product_id
        ]);
        $product->DelItems($product_id);
        $this->layout = false;
        $model = Orders::find()->all();
        if($order->delete()){
            Yii::$app->session->setFlash('soni', $_SESSION['cart.son']);
            return $this->render('cart', compact('model'));
        }
        else{
            return false;
        }
    }

    public function actionWishList(){
        $model = Orders::find()
        ->asArray()
        ->where(['user_id' => Yii::$app->user->identity->id])
        ->all();
        return $this->render('carts', compact('model'));
    }

    public function actionDelItems(){
        $id = Yii::$app->request->get('id');
        $order = Orders::findOne($id);
        $product = new Products();
        $product->DelItems($order->product_id);
        if($order->delete()){
            Yii::$app->session->setFlash('success', "Ma'lumot o'chirildi!");
            return $this->redirect(['cart/wish-list']);
        }
        else{
            Yii::$app->session->setFlash('success', "Ma'lumot o'chirilmadi!");
            return $this->redirect(['cart/wish-list']);
        }
    }

    public function actionOformit(){
        $id = Yii::$app->request->get('id');
        $order = Orders::findOne([
            'id' => $id
        ]);
        $product = Products::findOne([
            'id' => $order->product_id
        ]);

        $model = new OrderItem();

        if($model->load(Yii::$app->request->post())){
            Yii::$app->mailer->compose('order', ['session' => $_SESSION['cart']])
                ->setFrom(['admin@mail.ru' => 'Umidjon'])
                ->setTo($model->email)
                ->setSubject($model->product_name)
                ->send();
            $model->user_id = Yii::$app->user->identity->id;
            $model->product_id = $product->id;
            $model->status = 'active';
            $row = OrderItem::findOne([
                'user_id' => Yii::$app->user->identity->id,
                'product_id' => $product->id
            ]);
            if(!empty($row)){
                $row->soni += $model->soni;
                if($row->save()){
                    Yii::$app->session->setFlash('success', "Buyurtmangiz yuborildi!");
                    $product->DelItems($order->product_id);
                    $order->delete();
                    return $this->redirect(['cart/wish-list']);
                }
                else{
                    Yii::$app->session->setFlash('error', "Ma'lumotlar yuborilmadi!");
                    return $this->refresh();
                }
            }
            else{
                if($model->save()){
                    Yii::$app->session->setFlash('success', "Buyurtmangiz yuborildi!");
                    $product->DelItems($order->product_id);
                    $order->delete();
                    return $this->redirect(['cart/wish-list']);
                }
                else{
                    Yii::$app->session->setFlash('error', "Ma'lumotlar yuborilmadi!");
                    return $this->refresh();
                }
            }
        }
        return $this->render('ofor', compact('order', 'product', 'model'));
    }

    public function actionSaveAll(){
        $user_id = Yii::$app->user->identity->id;
        $product = new Products();
        $orders = Orders::find()
            ->asArray()
            ->where(['user_id' => $user_id])
            ->all();
        $model = new OrderItem();
        $array = [];

        if($model->load(Yii::$app->request->post())){
            $n = $model->fullname;
            $email = $model->email;
            $address = $model->address;
            $phone = $model->phone;
            foreach ($orders as $k => $r){
                $del = Orders::findOne($r['id']);
                $row = OrderItem::findOne([
                    'user_id' => $user_id,
                    'product_id' => $r['product_id'],
                    'status' => 'active'
                ]);
                if(!empty($row)){
                    $row->soni += $r['son'];
                    $row->save(false);
                }
                else{
                    $model->fullname = $n;
                    $model->email = $email;
                    $model->phone = $phone;
                    $model->address = $address;
                    $model->user_id = $user_id;
                    $model->product_name = $r['name'];
                    $model->product_id = $r['product_id'];
                    $model->sum = $r['sum'];
                    $model->soni = $r['son'];
                    $model->images = $r['images'];
                    $model->status = 'active';
                    if($model->save()){
                        $model = new OrderItem();
                    }
                }
                $product->DelItems($del->product_id);
                $del->delete();
            }
            Yii::$app->session->setFlash('success', "Buyurtmangiz qabul qilindi!");
            return $this->redirect(['main/index']);
        }
        return $this->render('save', compact('model', 'orders'));
    }
}

views/cart/cart.php
<?php
$count = 0; $sum = 0;
use yii\helpers\Url;
?>
<div class="cart-main-area pb-100">
    <div class="container">
        <!-- Section Title Start -->
        <div class="section-title mb-50">
            <h2>Xarid savatchasi</h2>
        </div>
        <!-- Section Title Start End -->
        <div class="row">
            <?php if(!empty($model)): ?>
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <!-- Form Start -->
                    <form action="#">
                        <!-- Table Content Start -->
                        <div class="table-content table-responsive mb-50">
                            <table>
                                <thead>
                                <tr>
                                    <th class="product-thumbnail">Rasm</th>
                                    <th class="product-name">Maxsulot nomi</th>
                                    <th class="product-price">Summasi</th>
                                    <th class="product-quantity">Soni</th>
                                    <th class="product-subtotal">Umumiy summasi</th>
                                    <th class="product-remove">O'chirish</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php if(isset($_SESSION['cart'])): ?>
                                    <?php if(!empty($_SESSION['cart'])): ?>
                                        <?php foreach ($_SESSION['cart'] as $k => $r): ?>
                                            <tr>
                                                <td class="product-thumbnail">
                                                    <a href="#"><img src="<?=Url::base()?>/img/new-products/2_2.jpg" alt="cart-image" /></a>
                                                </td>
                                                <td class="product-name"><a href="#"><?=$r['name']?></a></td>
                                                <td class="product-price"><span class="amount">$<?=$r['sum']?></span></td>
                                                <td class="product-quantity"><input type="number" value="<?=$r['son']?>" /></td>
                                                <td class="product-subtotal">$<?=$r['son'] * $r['sum']?></td>
                                                <td class="product-remove"> <a href="<?=Url::to(['cart/remove', 'id' => $k])?>" class="remove-product"><i class="fa fa-times" aria-hidden="true"></i></a></td>
                                            </tr>
                                        <?php endforeach; ?>
                                    <?php else: ?>
                                        <p class="alert alert-danger">
                                            Xarid savatchangiz bo'sh!
                                        </p>
                                    <?php endif; ?>
                                <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                        <!-- Table Content Start -->
                        <div class="row">
                            <!-- Cart Button Start -->
                            <div class="col-md-8 col-sm-7 col-xs-12">
                                <div class="buttons-cart">
                                    <input type="submit" value="Update Cart" />
                                    <a href="#">Continue Shopping</a>
                                </div>
                            </div>
                            <!-- Cart Button Start -->
                            <!-- Cart Totals Start -->
                            <div class="col-md-4 col-sm-5 col-xs-12">
                                <div class="cart_totals">
                                    <h2>Cart Totals</h2>
                                    <br />
                                    <table>
                                        <tbody>
                                        <tr class="cart-subtotal">
                                            <th>Jami Soni</th>
                                            <td><span class="amount" id="total-count"><?=$_SESSION['cart.son'] ?? $count; ?></span></td>
                                        </tr>
                                        <tr class="order-total">
                                            <th>Jami Summasi</th>
                                            <td>
                                                <strong><span class="amount">$<?=$_SESSION['cart.sum'] ?? $sum; ?></span></strong>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <div class="wc-proceed-to-checkout">
                                        <a href="#">Proceed to Checkout</a>
                                    </div>
                                </div>
                            </div>
                            <!-- Cart Totals End -->
                        </div>
                        <!-- Row End -->
                    </form>
                    <!-- Form End -->
                </div>
            <?php else: ?>
                <div class="col-xs-12">
                    <p class="alert alert-danger">
                        Xarid savatchasi bo'sh!
                    </p>
                </div>
            <?php endif; ?>
        </div>
        <!-- Row End -->
    </div>
</div>

views/cart/carts.php
<?php
$count = 0; $sum = 0;
use yii\helpers\Url;
?>
<div class="cart-main-area pb-100">
    <div class="container">
        <!-- Section Title Start -->
        <div class="section-title mb-50">
            <h2>Xarid savatchasi</h2>
            <?php if(Yii::$app->session->hasFlash('success')): ?>
                <p class="alert alert-warning">
                    <?=Yii::$app->session->getFlash('success'); ?>
                </p>
            <?php endif; ?>
        </div>
        <!-- Section Title Start End -->
        <div class="row">
            <?php if(!empty($model)): ?>
                <div class="col-md-12 col-sm-12 col-xs-12">
                <!-- Form Start -->
                <form action="#">
                    <!-- Table Content Start -->
                    <div class="table-content table-responsive mb-50">
                        <table>
                            <thead>
                            <tr>
                                <th class="product-thumbnail">Rasm</th>
                                <th class="product-name">Maxsulot nomi</th>
                                <th class="product-price">Summasi</th>
                                <th class="product-quantity">Soni</th>
                                <th class="product-subtotal">Umumiy summasi</th>
                                <th class="product-remove">O'chirish</th>
                                <th class="product-price">Buyurtma berish</th>
                            </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($model as $r): ?>
                                    <?php
                                    $count += $r['son'];
                                    $sum += $r['son'] * $r['sum'];
                                    ?>
                                    <tr>
                                        <td class="product-thumbnail">
                                            <a href="#"><img src="<?=Url::base()?>/img/new-products/2_2.jpg" alt="cart-image" /></a>
                                        </td>
                                        <td class="product-name"><a href="#"><?=$r['name']?></a></td>
                                        <td class="product-price"><span class="amount">$<?=$r['sum']?></span></td>
                                        <td class="product-quantity"><input type="number" value="<?=$r['son']?>" /></td>
                                        <td class="product-subtotal">$<?=$r['son'] * $r['sum']?></td>
                                        <td class="product-remove"> <a href="<?=Url::to(['cart/del-items', 'id' => $r['id']])?>"><i class="fa fa-times" aria-hidden="true"></i></a></td>
                                        <td class="product-price">
                                            <a href="<?=Url::to(['cart/oformit', 'id' => $r['id']])?>" class="btn btn-info btn-sm"><i class="fa fa-plus"></i></a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                    <!-- Table Content Start -->
                    <div class="row">
                        <!-- Cart Button Start -->
                        <div class="col-md-8 col-sm-7 col-xs-12">
                            <div class="buttons-cart">
                                <a href="<?=Url::to(['cart/save-all'])?>">Jami Mahsulotlarga Zakaz berish</a>
                            </div>
                        </div>
                        <!-- Cart Button Start -->
                        <!-- Cart Totals Start -->
                        <div class="col-md-4 col-sm-5 col-xs-12">
                            <div class="cart_totals">
                                <h2>Jami Mahsulot</h2>
                                <br />
                                <table>
                                    <tbody>
                                    <tr class="cart-subtotal">
                                        <th>Jami Soni</th>
                                        <td><span class="amount" id="total-count"><?=$_SESSION['cart.son'] ?? $count; ?></span></td>
                                    </tr>
                                    <tr class="order-total">
                                        <th>Jami Summasi</th>
                                        <td>
                                            <strong><span class="amount">$<?=$_SESSION['cart.sum'] ?? $sum; ?></span></strong>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- Cart Totals End -->
                    </div>
                    <!-- Row End -->
                </form>
                <!-- Form End -->
            </div>
            <?php else: ?>
                <div class="col-xs-12">
                    <p class="alert alert-danger">
                        Xarid savatchasi bo'sh!
                    </p>
                </div>
            <?php endif; ?>
        </div>
        <!-- Row End -->
    </div>
</div>

views/cart/ofor.php
<?php
    use yii\helpers\Url;
    use yii\helpers\Html;
?>
<div class="cart-main-area pb-100">
    <div class="container">
    <div class="section-title mb-50">
        <h2>Buyurtma berish</h2>
    </div>
    <div class="row">
        <?php if(Yii::$app->session->hasFlash('error')): ?>
            <p class="alert alert-warning">
                <?=Yii::$app->session->getFlash('error'); ?>
            </p>
        <?php endif; ?>
        <div class="col-sm-12">
            <div class="table-content table-responsive mb-50">
                <table>
                    <thead>
                    <tr>
                        <th class="product-thumbnail">Rasm</th>
                        <th class="product-name">Maxsulot nomi</th>
                        <th class="product-price">Summasi</th>
                        <th class="product-quantity">Soni</th>
                        <th class="product-price">Umumiy summasi</th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="product-thumbnail">
                                <a href="#"><img src="<?=Url::base()?>/img/new-products/2_2.jpg" alt="cart-image" /></a>
                            </td>
                            <td class="product-name"><a href="#"><?=$order->name?></a></td>
                            <td class="product-price"><span class="amount">$<?=$order->sum?></span></td>
                            <td class="product-quantity"><input type="number" value="<?=$order->son?>" /></td>
                            <td class="product-subtotal">$<?=$order->son * $order->sum?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-12">
            <?php
                $f = \yii\bootstrap\ActiveForm::begin();
                echo $f->field($model, 'fullname')->textInput(['value' => Yii::$app->user->identity->fullname]);
                echo $f->field($model, 'email')->textInput(['value' => Yii::$app->user->identity->email]);
                echo $f->field($model, 'phone')->textInput(['value' => Yii::$app->user->identity->phone]);
                echo $f->field($model, 'address')->textInput(['value' => Yii::$app->user->identity->adress]);
            echo $f->field($model, 'soni')->input('number', ['value' => $order->son, 'class' => 'numbers form-control']);
                echo $f->field($model, 'product_name')->textInput(['value' => $order->name, 'readonly' => true]);
                echo $f->field($model, 'sum')->textInput(['value' => $order->sum, 'readonly' => true]);
                echo $f->field($model, 'images')->textInput(['value' => $order->images, 'readonly' => true]);
                echo Html::submitButton('Buyurtma berish', ['class' => 'btn btn-info btn-sm']);

                \yii\bootstrap\ActiveForm::end();
            ?>
        </div>
    </div>
</div>
</div>

views/cart/save.php
<?php
$count = 0; $sum = 0;
use yii\helpers\Url;
use yii\helpers\Html;
?>
<div class="cart-main-area pb-100">
    <div class="container">
        <!-- Section Title Start -->
        <div class="section-title mb-50">
            <h2>Buyurtma berish</h2>
            <?php
                $f = \yii\bootstrap\ActiveForm::begin();
            echo $f->field($model, 'fullname')->textInput(['value' => Yii::$app->user->identity->fullname]);
            echo $f->field($model, 'email')->textInput(['value' => Yii::$app->user->identity->email]);
            echo $f->field($model, 'phone')->textInput(['value' => Yii::$app->user->identity->phone]);
            echo $f->field($model, 'address')->textInput(['value' => Yii::$app->user->identity->adress]);
            echo Html::submitButton('Buyurtma berish', ['class' => 'btn btn-info btn-sm']);



            \yii\bootstrap\ActiveForm::end();
            ?>
        </div>
        <!-- Section Title Start End -->
        <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <!-- Form Start -->
                    <form action="#">
                        <!-- Table Content Start -->
                        <div class="table-content table-responsive mb-50">
                            <table>
                                <thead>
                                <tr>
                                    <th class="product-thumbnail">Rasm</th>
                                    <th class="product-name">Maxsulot nomi</th>
                                    <th class="product-price">Summasi</th>
                                    <th class="product-quantity">Soni</th>
                                    <th class="product-subtotal">Umumiy summasi</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($orders as $r): ?>
                                    <?php
                                    $count += $r['son'];
                                    $sum += $r['son'] * $r['sum'];
                                    ?>
                                    <tr>
                                        <td class="product-thumbnail">
                                            <a href="#"><img src="<?=Url::base()?>/img/new-products/2_2.jpg" alt="cart-image" /></a>
                                        </td>
                                        <td class="product-name"><a href="#"><?=$r['name']?></a></td>
                                        <td class="product-price"><span class="amount">$<?=$r['sum']?></span></td>
                                        <td class="product-quantity"><input type="number" value="<?=$r['son']?>" /></td>
                                        <td class="product-subtotal">$<?=$r['son'] * $r['sum']?></td>

                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                        <!-- Table Content Start -->
                        <div class="row">
                        </div>
                        <!-- Row End -->
                    </form>
                    <!-- Form End -->
                </div>
        </div>
        <!-- Row End -->
    </div>
</div>